name: Run Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FUNCTION_NAME: 'cglabs-fordpoc-func'
  SCRIPT_PATH: 'code/.'
  RESOURCE_GROUP: 'FordLoggingPoc'
  LOCATION: 'eastus'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3

      - name: 'Verify Login Azure via SP'
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          enable-AzPSSession: true

